language: go
go:
  - 1.14.x
  - 1.15.x
services:
  - redis
env:
  - GO111MODULE=on
after_success:
  - go get golang.org/x/tools/cmd/cover 
  - go get github.com/mattn/goveralls
  - go test -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci